version: "3.6"
services:
  postgres:
      image: postgres:10.5
      ports:
        - "${POSTGRES_PORT}:5432"
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      hostname: ${POSTGRES_PASSWORD}
      volumes:
        - ./postgres/init:/docker-entrypoint-initdb.d
        - ./postgres/data:/var/lib/postgresql/data
