version: "3.6"
services:
  keiba-db:
    image: postgres:10.5
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: ${POSTGRES_HOSTNAME}
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data

  pgweb:
    image: sosedoff/pgweb
    ports:
      - "${PGWEB_PORT}:8081"
    environment:
      DATABASE_URL: postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOSTNAME}:5432/${POSTGRES_DATABASE}?sslmode=disable
      AUTH_USER: ${PGWEB_USERNAME}
      AUTH_PASS: ${PGWEB_PASSWORD}
    depends_on:
      - keiba-db
